### ISSUE TITLE
[REST] - Implementação de Versionamento nos Endpoints

### ISSUE THREAD

**Issue by diegosneves** [diegosneves/conectar-doacoes#25]
Esta tarefa envolve a implementação de versionamento nos endpoints da nossa aplicação. O versionamento permite que façamos alterações significativas nos nossos endpoints sem interromper os serviços já em uso. Isso será feito adicionando prefixos de versão (`/v1`, `/v2`, etc.) aos nossos endpoints. Segue a lista de tarefas para esta issue:

- [x] **Estudar os Padrões de Versionamento**
    - Comece esta tarefa pesquisando e estudando os diferentes padrões de versionamento para APIs REST. Isto inclui padrões como Versionamento pela URI, pelo cabeçalho `Accept` , pelo cabeçalho personalizado e pelo cabeçalho `Content-Type`. Escolha o padrão que mais se adequa às necessidades da nossa aplicação.

- [x] **Implementar o Versionamento nos Endpoints**
    - Depois de escolher um padrão de versionamento, implemente-o em nossos endpoints. Isso envolve a adição de um prefixo de versão (como `/v1` ou `/v2`) à URI de cada endpoint.

- [x] **Testar os Endpoints Versionados**
    - Após implementar o versionamento, verifique se ele funciona como esperado. Faça isso testando cada endpoint versionado and garantindo que ele responde da maneira correta.

**Comment by GuilhermeBauer16** [comment]
# Materiais utilizados na pesquisa da spike:

* Texto com a explicação de como funciona o versionamento de Endpoints: https://medium.com/@alrazak/understanding-rest-api-versioning-25b12b939c8d

* Vídeo com explicação e demonstração: https://www.youtube.com/watch?v=ySo4-G6Ycfw&ab_channel=WebDevCody
